name: Docker Build

on:
  push:
    branches: [ "LabDevOps" ]
  pull_request:
    branches: [ "LabDevOps" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: app-js:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max